name: "secrets"
version: "3.0.0"
usage: "Secrets encryption in Helm for Git storing"
description: |-
  This plugin provides secrets values encryption for Helm charts secure storing

command: "$HELM_PLUGIN_DIR/scripts/run.sh"

hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install.sh"
  update: "$HELM_PLUGIN_DIR/scripts/install.sh"

useTunnel: false

