name: Push to GH Wiki

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: sync wiki
        run: rsync -av --delete --exclude=.git docs/ wiki/

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatically publish wiki" && git push
        working-directory: wiki
